name: Self Hosted Integration Runtime Deployment

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'infra/SelfHostedIntegrationRuntime/**'
      - 'infra/DataFactory/**'
      - '.ado/workflows/selfHostedIntegrationRuntimeDeployment.yml'

variables:
  AZURE_RESOURCE_MANAGER_CONNECTION_NAME: 'Marvins Azure Subscription(558bd446-4212-46a2-908c-9ab0a628705e)'
  AZURE_SUBSCRIPTION_ID: '558bd446-4212-46a2-908c-9ab0a628705e'
  AZURE_RESOURCE_GROUP_NAME: 'datahub-shir'
  AZURE_LOCATION: 'North Europe'

stages:
  - stage: Validation
    displayName: 'Validation of ARM templates'
    jobs:
      - job: Validation
        displayName: 'Validation of ARM templates'
        continueOnError: false
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
        # Checkout code
        - checkout: self
          name: checkout_repository
          displayName: 'Checkout repository'
          submodules: true
          lfs: false
          clean: true
          continueOnError: false
          enabled: true
        
        # Deploy data factory - validation
        - task: AzureResourceManagerTemplateDeployment@3
          name: data_factory_validation
          displayName: Deploy data factory - validation
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/DataFactory/deploy.dataFactory.json'
            csmParametersFile: 'infra/DataFactory/params.dataFactory001.json'
            deploymentMode: 'Validation'
        
        # Deploy vmss - validation
        - task: AzureResourceManagerTemplateDeployment@3
          name: vmss_validation
          displayName: Deploy vmss - validation
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/SelfHostedIntegrationRuntime/deploy.vmss.json'
            csmParametersFile: 'infra/SelfHostedIntegrationRuntime/params.vmss.json'
            deploymentMode: 'Validation'

  - stage: Deployment
    displayName: 'Deployment of ARM templates'
    dependsOn: Validation
    condition: succeeded()
    jobs:
      - job: Deployment
        displayName: 'Deployment of ARM templates'
        continueOnError: false
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
        # Checkout repository
        - checkout: self
          name: checkout_repository
          displayName: 'Checkout repository'
          submodules: true
          lfs: false
          clean: true
          continueOnError: false
          enabled: true
        
        # Deploy data factory
        - task: AzureResourceManagerTemplateDeployment@3
          name: data_factory_deployment
          displayName: Deploy data factory
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/DataFactory/deploy.dataFactory.json'
            csmParametersFile: 'infra/DataFactory/params.dataFactory001.json'
            deploymentMode: 'Incremental'
        
        # Deploy vmss
        - task: AzureResourceManagerTemplateDeployment@3
          name: vmss_deployment
          displayName: Deploy vmss
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/SelfHostedIntegrationRuntime/deploy.vmss.json'
            csmParametersFile: 'infra/SelfHostedIntegrationRuntime/params.vmss.json'
            deploymentMode: 'Incremental'
