name: Virtual Network Deployment

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'infra/VirtualNetwork/**'
      - '.ado/workflows/vnetDeployment.yml'

variables:
  AZURE_RESOURCE_MANAGER_CONNECTION_NAME: 'Marvins Azure Subscription(558bd446-4212-46a2-908c-9ab0a628705e)'
  AZURE_SUBSCRIPTION_ID: '558bd446-4212-46a2-908c-9ab0a628705e'
  AZURE_RESOURCE_GROUP_NAME: 'datahub-network'
  AZURE_LOCATION: 'North Europe'

stages:
  - stage: Validation
    displayName: 'Validation of ARM templates'
    jobs:
      - job: Validation
        displayName: 'Validation of ARM templates'
        continueOnError: false
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
        # Checkout code
        - checkout: self
          name: checkout_repository
          displayName: 'Checkout repository'
          submodules: true
          lfs: false
          clean: true
          continueOnError: false
          enabled: true
        
        # Deploy vnet - validation
        - task: AzureResourceManagerTemplateDeployment@3
          name: vnet_validation
          displayName: Deploy vnet - validation
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/VirtualNetwork/deploy.vnet.json'
            csmParametersFile: 'infra/VirtualNetwork/params.vnet.json'
            deploymentMode: 'Validation'
        
        # Deploy vnet peering 001 - validation
        - task: AzureResourceManagerTemplateDeployment@3
          name: vnet_peering_001_validation
          displayName: Deploy vnet peering 001 - validation
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/VirtualNetwork/deploy.vnetPeering.json'
            csmParametersFile: 'infra/VirtualNetwork/params.vnetPeering001.json'
            deploymentMode: 'Validation'

  - stage: Deployment
    displayName: 'Deployment of ARM templates'
    dependsOn: Validation
    condition: succeeded()
    jobs:
      - job: Deployment
        displayName: 'Deployment of ARM templates'
        continueOnError: false
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
        # Checkout repository
        - checkout: self
          name: checkout_repository
          displayName: 'Checkout repository'
          submodules: true
          lfs: false
          clean: true
          continueOnError: false
          enabled: true
        
        # Deploy vnet
        - task: AzureResourceManagerTemplateDeployment@3
          name: vnet_deployment
          displayName: Deploy vnet
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/VirtualNetwork/deploy.vnet.json'
            csmParametersFile: 'infra/VirtualNetwork/params.vnet.json'
            deploymentMode: 'Incremental'
        
        # Deploy vnet peering
        - task: AzureResourceManagerTemplateDeployment@3
          name: vnet_peering_001_deployment
          displayName: Deploy vnet peering 001
          enabled: true
          continueOnError: false
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '$(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)'
            subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(AZURE_RESOURCE_GROUP_NAME)'
            location: '$(AZURE_LOCATION)'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/VirtualNetwork/deploy.vnetPeering.json'
            csmParametersFile: 'infra/VirtualNetwork/params.vnetPeering001.json'
            deploymentMode: 'Incremental'
