name: Data Hub Deployment

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - "code/**"
      - ".github/workflows/dataHubDeployment.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - "code/**"
      - ".github/workflows/dataHubDeployment.yml"

env:
  AZURE_SUBSCRIPTION_ID: "4060c03e-0d2e-44b7-82a3-da9376fe50b2" # Update to '{dataHubSubscriptionId}'
  AZURE_LOCATION: "northeurope"                                 # Update to '{regionName}'
  DATA_MANAGEMENT_ZONE_PREFIX: "dh"                             # Update to '{yourDataManegementZonePrefix}'

jobs:
  validation:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Data Management Zone - validation
      - name: Deploy Data Management Zone - validation
        id: data_management_zone_validation
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.json
          parameters: ${{ github.workspace }}/infra/params.dev.json prefix="${{ env.DATA_MANAGEMENT_ZONE_PREFIX }}"
          deploymentMode: Validate

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout

  deployment:
    needs: [validation]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Deploy Data Management Zone - validation
      - name: Deploy Data Management Zone - validation
        id: data_management_zone_validation
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/main.json
          parameters: ${{ github.workspace }}/infra/params.dev.json prefix="${{ env.DATA_MANAGEMENT_ZONE_PREFIX }}"
          deploymentMode: Incremental

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout
