name: Data Hub Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/KeyVault/**'
      - 'infra/SelfHostedIntegrationRuntime/**'
      - 'infra/DataFactory/**'
      - 'infra/Storage/**'
      - 'infra/PrivateEndpoint/**'
      - '.github/workflows/dataHubDeployment.yml'

env:
  AZURE_SUBSCRIPTION_ID: ''
  AZURE_RESOURCE_GROUP_NAME_MANAGEMENT: dh-mgmt
  AZURE_LOCATION: northeurope

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create resource group
    - name: Create resource group
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }}"
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }}
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  validation:
    needs: [ create-resource-group ]
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy key vault 001 - validation
    - name: Deploy key vault 001 - validation
      id: key_vault_001_validation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/KeyVault/deploy.keyVault.json \
            --parameters $GITHUB_WORKSPACE/infra/KeyVault/params.keyVault001.json
    
    # Deploy storage account 001 - validation
    - name: Deploy storage account 001 - validation
      id: storage_001_validation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Deploy data factory 001 - validation
    - name: Deploy data factory 001 - validation
      id: data_factory_001_validation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/DataFactory/deploy.dataFactory.json \
            --parameters $GITHUB_WORKSPACE/infra/DataFactory/params.dataFactory001.json
    
    # Deploy shir 001 - validation
    - name: Deploy shir 001 - validation
      id: shir_001_validation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/deploy.shir.json \
            --parameters $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/params.shir001.json
      continue-on-error: true
    
    # Deploy function 001 - validation
    - name: Deploy function 001 - validation
      id: function_001_validation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/Function/deploy.function.json \
            --parameters $GITHUB_WORKSPACE/infra/Function/params.function001.json
    
    # # Deploy power bi 001 - validation
    # - name: Deploy power bi 001 - validation
    #   id: power_bi_validation
    #   uses: azure/cli@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       echo "Creating deployment in resource group"
    #       az deployment group validate \
    #         --mode Incremental \
    #         --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
    #         --template-file $GITHUB_WORKSPACE/infra/Function/deploy.powerBi.json \
    #         --parameters $GITHUB_WORKSPACE/infra/Function/params.powerBi001.json
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  deployment:
    needs: [ create-resource-group, validation ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 
    
    # Deploy key vault 001
    - name: Deploy key vault 001
      id: key_vault_001_deployment
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/KeyVault/deploy.keyVault.json \
            --parameters $GITHUB_WORKSPACE/infra/KeyVault/params.keyVault001.json
    
    # Deploy storage account 001
    - name: Deploy storage account 001
      id: storage_account_001_deployment
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Upload file to storage account 001
    - name: Upload file to storage account 001
      id: upload_file_001
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: |
          "Uploading file to storage account"
          $storageAccount = Get-AzStorageAccount -ResourceGroupName "dh-mgmt" -Name "datahubstorage001"
          $ctx = $storageAccount.Context
          Set-AzStorageBlobContent -File "infra/SelfHostedIntegrationRuntime/gatewayInstall.ps1" -Container scripts -Blob "gatewayInstall.ps1" -Context $ctx -Force
    
    # Deploy data factory 001
    - name: Deploy data factory 001
      id: data_factory_001_deployment
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/DataFactory/deploy.dataFactory.json \
            --parameters $GITHUB_WORKSPACE/infra/DataFactory/params.dataFactory001.json
    
    # Deploy shir 001
    - name: Deploy shir 001
      id: shir_001_deployment
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/deploy.shir.json \
            --parameters $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/params.shir001.json
    
    # Deploy function 001
    - name: Deploy function 001
      id: function_001_deployment
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
            --template-file $GITHUB_WORKSPACE/infra/Function/deploy.function.json \
            --parameters $GITHUB_WORKSPACE/infra/Function/params.function001.json
    
    # # Deploy power bi 001
    # - name: Deploy power bi 001
    #   id: power_bi_001_deployment
    #   uses: azure/cli@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       echo "Creating deployment in resource group"
    #       az deployment group create \
    #         --mode Incremental \
    #         --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }} \
    #         --template-file $GITHUB_WORKSPACE/infra/Function/deploy.powerBi.json \
    #         --parameters $GITHUB_WORKSPACE/infra/Function/params.powerBi001.json
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
