name: Data Hub Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/ContainerRegistry/**'
      - 'infra/KeyVault/**'
      - 'infra/Purview/**'
      - 'infra/SynapsePrivateLinkHub/**'
      - '.github/workflows/dataHubDeployment.yml'
      - 'code/GeneratePassword.ps1'

env:
  AZURE_SUBSCRIPTION_ID: '4060c03e-0d2e-44b7-82a3-da9376fe50b2'
  AZURE_RESOURCE_GROUP_NAME_AUTOMATION: 'dh-automation'
  AZURE_RESOURCE_GROUP_NAME_MANAGEMENT: 'dh-mgmt'
  AZURE_RESOURCE_GROUP_NAME_CONSUMPTION: 'dh-consumption'
  AZURE_RESOURCE_GROUP_NAME_CONTAINER: 'dh-container'
  AZURE_RESOURCE_GROUP_NAME_GOVERNANCE: 'dh-governance'
  AZURE_LOCATION: 'northeurope'

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    steps:
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create resource group
    - name: Create resource group
      id: resource_group_automation
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group \"${{ env.AZURE_RESOURCE_GROUP_NAME_AUTOMATION }}\""
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_AUTOMATION }}
    
    # Create resource group
    - name: Create resource group
      id: resource_group_management
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group \"${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }}\""
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_MANAGEMENT }}
    
    # Create resource group
    - name: Create resource group
      id: resource_group_consumption
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group \"${{ env.AZURE_RESOURCE_GROUP_NAME_CONSUMPTION }}\""
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_CONSUMPTION }}
    
    # Create resource group
    - name: Create resource group
      id: resource_group_container
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group \"${{ env.AZURE_RESOURCE_GROUP_NAME_CONTAINER }}\""
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_CONTAINER }}
    
    # Create resource group
    - name: Create resource group
      id: resource_group_governance
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group \"${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}\""
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  validation:
    needs: [ create-resource-group ]
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy Key Vault 001 - validation
    - name: Deploy Key Vault 001 - validation
      id: key_vault_001_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/KeyVault/deploy.keyVault.json
        parameters: ${{ github.workspace }}/infra/KeyVault/params.keyVault001.json
        deploymentMode: Validate
    
    # Deploy Purview 001 - validation
    - name: Deploy Purview 001 - validation
      id: purview_001_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/Purview/deploy.purview.json
        parameters: ${{ github.workspace }}/infra/Purview/params.purview001.json
        deploymentMode: Validate
    
    # Deploy Container Registry 001 - validation
    - name: Deploy Container Registry  001 - validation
      id: container_registry_001_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_CONTAINER }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/ContainerRegistry/deploy.containerRegistry.json
        parameters: ${{ github.workspace }}/infra/ContainerRegistry/params.containerRegistry001.json
        deploymentMode: Validate
    
    # Deploy Synapse Private Link Hub 001 - validation
    - name: Deploy Synapse Private Link Hub 001 - validation
      id: synapse_private_link_hub_001_validation
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_CONSUMPTION }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/SynapsePrivateLinkHub/deploy.synapsePrivateLinkHub.json
        parameters: ${{ github.workspace }}/infra/SynapsePrivateLinkHub/params.synapsePrivateLinkHub001.json
        deploymentMode: Validate
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  deployment:
    needs: [ create-resource-group, validation ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    # Deploy Key Vault 001
    - name: Deploy Key Vault 001
      id: key_vault_001_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/KeyVault/deploy.keyVault.json
        parameters: ${{ github.workspace }}/infra/KeyVault/params.keyVault001.json
        deploymentMode: Incremental
    
    # Deploy Purview 001
    - name: Deploy Purview 001
      id: purview_001_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_GOVERNANCE }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/Purview/deploy.purview.json
        parameters: ${{ github.workspace }}/infra/Purview/params.purview001.json
        deploymentMode: Incremental
    
    # Deploy Container Registry 001
    - name: Deploy Container Registry  001
      id: container_registry_001_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_CONTAINER }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/ContainerRegistry/deploy.containerRegistry.json
        parameters: ${{ github.workspace }}/infra/ContainerRegistry/params.containerRegistry001.json
        deploymentMode: Incremental
    
    # Deploy Synapse Private Link Hub 001
    - name: Deploy Synapse Private Link Hub 001
      id: synapse_private_link_hub_001_deployment
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME_CONSUMPTION }}
        region: ${{ env.AZURE_LOCATION }}
        template: ${{ github.workspace }}/infra/SynapsePrivateLinkHub/deploy.synapsePrivateLinkHub.json
        parameters: ${{ github.workspace }}/infra/SynapsePrivateLinkHub/params.synapsePrivateLinkHub001.json
        deploymentMode: Incremental
    
    # Log out from Azure
    - name: Log out from Azure
      id: azure_logout
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
