name: Self Hosted Integration Runtime Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/SelfHostedIntegrationRuntime/**'
      - 'infra/DataFactory/**'
      - 'infra/Storage/**'
      - '.github/workflows/selfHostedIntegrationRuntimeDeployment.yml'

env:
  AZURE_RESOURCE_GROUP: datahub-shir
  AZURE_LOCATION: northeurope

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create resource group
    - name: Create resource group
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating resource group ${{ env.AZURE_RESOURCE_GROUP }}"
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP }}
    
    # Log out from Azure
    - name: Log out from Azure
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  validation:
    needs: [ create-resource-group ]
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy storage account - validation
    - name: Deploy storage account - validation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Deploy data factory - validation
    - name: Deploy data factory - validation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/DataFactory/deploy.dataFactory.json \
            --parameters $GITHUB_WORKSPACE/infra/DataFactory/params.dataFactory001.json
    
    # Deploy vmss - validation
    - name: Deploy vmss - validation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group validate \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/deploy.vmss.json \
            --parameters $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/params.vmss.json
    
    # Log out from Azure
    - name: Log out from Azure
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout

  deployment:
    needs: [ create-resource-group, validation ]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy storage account
    - name: Deploy storage account
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/Storage/deploy.storage.json \
            --parameters $GITHUB_WORKSPACE/infra/Storage/params.storage001.json
    
    # Upload file to storage account
    - name: Upload file to storage account
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Uploading file to storage account"
          az storage blob upload \
            --account-name datahubshirstorageaccount \
            --container-name shir \
            --name gatewayInstall.ps1 \
            --file infra/SelfHostedIntegrationRuntime/gatewayInstall.ps1 \
            --auth-mode login
    
    # Deploy data factory
    - name: Deploy data factory
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/DataFactory/deploy.dataFactory.json \
            --parameters $GITHUB_WORKSPACE/infra/DataFactory/params.dataFactory001.json
    
    # Deploy vmss
    - name: Deploy vmss
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating deployment in resource group"
          az deployment group create \
            --mode Incremental \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/deploy.vmss.json \
            --parameters $GITHUB_WORKSPACE/infra/SelfHostedIntegrationRuntime/params.vmss.json
    
    # Log out from Azure
    - name: Log out from Azure
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az logout
