name: Test_replace

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  AZURE_SUBSCRIPTION_ID: "4060c03e-0d2e-44b7-82a3-da9376fe50b2" # Update to '{dataHubSubscriptionId}'
  AZURE_RESOURCE_GROUP_NAME_NETWORK: "dh-network" # Update to '{dataHubName}-network'
  AZURE_RESOURCE_GROUP_NAME_GLOBAL_DNS: "dh-global-dns" # Update to '{dataHubName}-global-dns'
  AZURE_RESOURCE_GROUP_NAME_AUTOMATION: "dh-automation" # Update to '{dataHubName}-automation'
  AZURE_RESOURCE_GROUP_NAME_MANAGEMENT: "dh-mgmt" # Update to '{dataHubName}-mgmt'
  AZURE_RESOURCE_GROUP_NAME_CONSUMPTION: "dh-consumption" # Update to '{dataHubName}-consumption'
  AZURE_RESOURCE_GROUP_NAME_CONTAINER: "dh-container" # Update to '{dataHubName}-container'
  AZURE_RESOURCE_GROUP_NAME_GOVERNANCE: "dh-governance" # Update to '{dataHubName}-governance'
  AZURE_LOCATION: "northeurope" # Update to '{regionName}'
  AZURE_TAGS: '"CostCenter":"ABCDE-12345", "Owner":"EnterpriseScaleAnalytics"'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      
      - name: Test
        run: |
          echo ${{ env.AZURE_TAGS }}
      
      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Test
        run: |
          echo ${{ env.AZURE_TAGS }}
      
      # Deploy Resource Groups
      - name: Deploy Resource Groups
        id: resource_groups_deployment
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.AZURE_LOCATION }}
          template: ${{ github.workspace }}/infra/ResourceGroups/deploy.resourceGroups.json
          parameters: ${{ github.workspace }}/infra/ResourceGroups/params.resourceGroups001.json tags="{ ${{ toJSON(env.AZURE_TAGS) }} }"
